site_name: No Room for a Wallflower
theme: readthedocs
nav:
  - 'index.md'
  - 'People':
    - 'Landmark Colonial':
      - 'people/patience.md'
      - 'people/edena-ji.md'
      - 'people/brava-hadura.md'
    - 'Groups of Interest':
      - 'factions/landmark-colonial.md'
  - 'Places':
    - 'places/evergreen.md'
  - 'Things':
    - 'things/hercynia.md'
    - 'things/egregorians.md'
