site_name: No Room for a Wallflower
theme: readthedocs
nav:
  - 'index.md'
  - 'People':
    - 'Landmark Colonial':
      - 'people/landmark/patience.md'
      - 'people/landmark/edena-ji.md'
      - 'people/landmark/brava-hadura.md'
    - 'Groups of Interest':
      - 'factions/landmark-colonial.md'
      - 'factions/huc.md'
  - 'Places':
    - 'places/evergreen.md'
    - 'Gray Towns':
      - 'places/gray-towns/merricktown.md'
      - 'places/gray-towns/liu-maize.md'
  - 'Things':
    - 'things/hercynia.md'
    - 'things/egregorians.md'
